name: fruits_hub_dashboard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  bloc: ^9.0.0
  cloud_firestore: ^5.6.7
  dartz: ^0.10.1
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  image_picker: ^1.1.2
  modal_progress_hud_nsn: ^0.5.1
  path: ^1.9.0
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
